version: '3'

services:
  aggregator:
    build:
      context: ./Aggregator
    ports:
      - "5006:5006"
    expose:
      - "5006"
    volumes:
      - ./persistent_data/code_logs/agg:/aggregator/logs
  kg:
    build:
      context: ./kg
    ports:
      - "5005:5005"
    expose:
      - "5005"
    links:
      - neo4j
      - aggregator
    volumes:
      - ./persistent_data/code_logs/kg:/kg/logs
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/ioana123
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./persistent_data/data:/data
      - ./persistent_data/logs:/logs
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - kg
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email mtopor98@gmail.com -d 82.79.70.62 --agree-tos
