# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_formats_client_pb2 as data__formats__client__pb2


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestKeywords = channel.unary_unary(
                '/ClientService/RequestKeywords',
                request_serializer=data__formats__client__pb2.Empty.SerializeToString,
                response_deserializer=data__formats__client__pb2.Statement.FromString,
                )
        self.ParseKeywords = channel.unary_unary(
                '/ClientService/ParseKeywords',
                request_serializer=data__formats__client__pb2.EntityResponse.SerializeToString,
                response_deserializer=data__formats__client__pb2.Empty.FromString,
                )


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestKeywords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseKeywords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestKeywords': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestKeywords,
                    request_deserializer=data__formats__client__pb2.Empty.FromString,
                    response_serializer=data__formats__client__pb2.Statement.SerializeToString,
            ),
            'ParseKeywords': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseKeywords,
                    request_deserializer=data__formats__client__pb2.EntityResponse.FromString,
                    response_serializer=data__formats__client__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestKeywords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientService/RequestKeywords',
            data__formats__client__pb2.Empty.SerializeToString,
            data__formats__client__pb2.Statement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ParseKeywords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientService/ParseKeywords',
            data__formats__client__pb2.EntityResponse.SerializeToString,
            data__formats__client__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
