# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_formats_client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64\x61ta_formats_client.proto\"\x07\n\x05\x45mpty\"\x19\n\tStatement\x12\x0c\n\x04type\x18\x01 \x01(\t\"&\n\x06\x45ntity\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\"+\n\x0e\x45ntityResponse\x12\x19\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x07.Entity2`\n\rClientService\x12%\n\x0fRequestKeywords\x12\x06.Empty\x1a\n.Statement\x12(\n\rParseKeywords\x12\x0f.EntityResponse\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_formats_client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=29
  _globals['_EMPTY']._serialized_end=36
  _globals['_STATEMENT']._serialized_start=38
  _globals['_STATEMENT']._serialized_end=63
  _globals['_ENTITY']._serialized_start=65
  _globals['_ENTITY']._serialized_end=103
  _globals['_ENTITYRESPONSE']._serialized_start=105
  _globals['_ENTITYRESPONSE']._serialized_end=148
  _globals['_CLIENTSERVICE']._serialized_start=150
  _globals['_CLIENTSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
