# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_formats_pb2 as data__formats__pb2


class MainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKeywords = channel.unary_unary(
                '/MainService/GetKeywords',
                request_serializer=data__formats__pb2.Statement.SerializeToString,
                response_deserializer=data__formats__pb2.EntityResponse.FromString,
                )


class MainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKeywords(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKeywords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeywords,
                    request_deserializer=data__formats__pb2.Statement.FromString,
                    response_serializer=data__formats__pb2.EntityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKeywords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MainService/GetKeywords',
            data__formats__pb2.Statement.SerializeToString,
            data__formats__pb2.EntityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
